# Generated by Django 5.1.2 on 2024-10-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("documento", models.TextField(max_length=30)),
                ("nombre", models.TextField(max_length=100)),
                ("edad", models.IntegerField()),
                ("eps", models.TextField(max_length=100)),
            ],
        ),
    ]
