# Generated by Django 5.1.2 on 2024-10-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("documento", models.TextField(max_length=50)),
                ("testname", models.TextField(max_length=100)),
                ("testretult", models.IntegerField()),
            ],
        ),
    ]
