# Generated by Django 5.1.2 on 2024-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hce", "0002_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagenes/"),
        ),
    ]
